<?php if(!$this->session->userdata('id')) { redirect(base_url().'admin'); } ?>
<section class="content-header"><div class="content-header-left"><h1>Edit Product</h1></div><div class="content-header-right"><a href="<?php echo base_url(); ?>admin/shop_product" class="btn btn-primary btn-sm">View All</a></div></section>
<section class="content"><div class="row"><div class="col-md-12">
<?php if(session()->getFlashdata('error')): ?><div class="callout callout-danger"><p><?php echo session()->getFlashdata('error'); ?></p></div><?php endif; ?>
<?php echo form_open_multipart(base_url().'admin/shop_product/edit/'.$product['product_id'],array('class'=>'form-horizontal')); ?>
<div class="box box-info"><div class="box-body">
<div class="form-group"><label class="col-sm-2 control-label">Product Name <span>*</span></label><div class="col-sm-6"><input type="text" class="form-control" name="product_name" value="<?php echo $product['product_name']; ?>"></div></div>
<div class="form-group"><label class="col-sm-2 control-label">Slug</label><div class="col-sm-6"><input type="text" class="form-control" name="product_slug" value="<?php echo $product['product_slug']; ?>"></div></div>
<div class="form-group"><label class="col-sm-2 control-label">Price <span>*</span></label><div class="col-sm-2"><input type="text" class="form-control" name="price" value="<?php echo $product['price']; ?>"></div></div>
<div class="form-group"><label class="col-sm-2 control-label">Stock Quantity</label><div class="col-sm-2"><input type="number" class="form-control" name="stock_quantity" value="<?php echo $product['stock_quantity']; ?>"></div></div>
<div class="form-group"><label class="col-sm-2 control-label">Parent Category</label><div class="col-sm-4"><select name="parent_category_id" id="parent_category_id" class="form-control select2"><option value="">Select</option><?php foreach($parent_categories as $row): ?><option value="<?php echo $row['parent_category_id']; ?>" <?php if(!empty($category_mapping['parent_category_id']) && $category_mapping['parent_category_id']==$row['parent_category_id']) echo 'selected'; ?>><?php echo $row['category_name']; ?></option><?php endforeach; ?></select></div></div>
<div class="form-group"><label class="col-sm-2 control-label">Sub Category</label><div class="col-sm-4"><select name="sub_category_id" id="sub_category_id" class="form-control select2"><option value="">Select</option><?php foreach($sub_categories as $row): ?><option value="<?php echo $row['sub_category_id']; ?>" data-parent="<?php echo $row['parent_category_id']; ?>" <?php if(!empty($category_mapping['sub_category_id']) && $category_mapping['sub_category_id']==$row['sub_category_id']) echo 'selected'; ?>><?php echo $row['category_name']; ?></option><?php endforeach; ?></select></div></div>
<div class="form-group"><label class="col-sm-2 control-label">Short Description <span>*</span></label><div class="col-sm-9"><textarea class="form-control" name="short_description" style="height:80px;"><?php echo $product['short_description']; ?></textarea></div></div>
<div class="form-group"><label class="col-sm-2 control-label">Full Description</label><div class="col-sm-9"><textarea class="form-control editor" name="full_description"><?php echo $product['full_description']; ?></textarea></div></div>
<div class="form-group"><label class="col-sm-2 control-label">Existing Featured Image</label><div class="col-sm-9"><img src="<?php echo base_url(); ?>public/uploads/<?php echo $product['featured_image']; ?>" style="width:150px;"></div></div>
<div class="form-group"><label class="col-sm-2 control-label">Featured Image</label><div class="col-sm-9"><input type="file" name="featured_image"></div></div>
<div class="form-group"><label class="col-sm-2 control-label">Gallery Images</label><div class="col-sm-9"><input type="file" name="photos[]" multiple>
<?php if(!empty($product_images)): ?><div style="margin-top:15px;"><?php foreach($product_images as $img): ?><div style="display:inline-block;margin:5px;text-align:center;"><img src="<?php echo base_url(); ?>public/uploads/shop_product_photos/<?php echo $img['image_name']; ?>" style="width:80px;"><br><a href="<?php echo base_url(); ?>admin/shop_product/delete_image/<?php echo $img['image_id']; ?>" class="btn btn-danger btn-xs" onclick="return confirm('Delete?');">Delete</a></div><?php endforeach; ?></div><?php endif; ?>
</div></div>
<div class="form-group"><label class="col-sm-2 control-label">Sort Order</label><div class="col-sm-2"><input type="number" class="form-control" name="sort_order" value="<?php echo $product['sort_order']; ?>"></div></div>
<div class="form-group"><label class="col-sm-2 control-label">Status</label><div class="col-sm-2"><select name="status" class="form-control"><option value="1" <?php if($product['status']==1) echo 'selected'; ?>>Enabled</option><option value="0" <?php if($product['status']==0) echo 'selected'; ?>>Disabled</option></select></div></div>
<div class="form-group"><label class="col-sm-2 control-label">Meta Title</label><div class="col-sm-9"><input type="text" class="form-control" name="meta_title" value="<?php echo $product['meta_title']; ?>"></div></div>
<div class="form-group"><label class="col-sm-2 control-label">Meta Keywords</label><div class="col-sm-9"><textarea class="form-control" name="meta_keyword" style="height:80px;"><?php echo $product['meta_keyword']; ?></textarea></div></div>
<div class="form-group"><label class="col-sm-2 control-label">Meta Description</label><div class="col-sm-9"><textarea class="form-control" name="meta_description" style="height:80px;"><?php echo $product['meta_description']; ?></textarea></div></div>
<div class="form-group"><label class="col-sm-2 control-label"></label><div class="col-sm-6"><button type="submit" class="btn btn-success" name="form1">Update</button></div></div>
</div></div><?php echo form_close(); ?></div></div></section>
